spring.application.name=notification-service

eureka.client.service-url.defaultZone=http://eureka:8761/eureka/

# RabbitMQ
spring.cloud.stream.defaultBinder=rabbit
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Email konfiguracija (Gmail primer - koristi App Password)
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e86b99f4a932a2
spring.mail.password=ff3b8873132713
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Stream konfiguracija - imena queue-eva
app.notification.exchange=notification.exchange
app.notification.queue=notification.queue
app.notification.routing-key=notification.routingKey

logging.level.root=INFO
logging.level.com.example.notificationservice=DEBUG