server.port=8761

# Eureka Server ne registruje sam sebe jer je centralni server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Opcionalno: ime aplikacije u Eureki
spring.application.name=eureka-server